In [172]:
import sys,os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error

class simpleNet:
    def __init__(self):
        #重みWが定義される
        self.W = np.random.randn(2,3) #ガウス分布で初期化
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)   
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        return loss
    
def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    #二重ループを用いずに二次元配列の全要素を触る
    #https://docs.scipy.org/doc/numpy/reference/generated/numpy.nditer.html
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val # 値を元に戻す
        it.iternext()   
        
    return grad

In [173]:
net = simpleNet()

In [174]:
print(net.W) #重みパラメータ

[[-1.59690693 -0.28623791 -0.74587346]
 [ 0.28536994  1.07691132  0.43236338]]


In [175]:
x = np.array([0.6, 0.9])
p = net.predict(y)
print(p)

[-0.70131121  0.79747744 -0.05839703]


In [176]:
np.argmax(p) #最大値のインデックス

1

In [177]:
t = np.array([0, 0, 1]) #正解ラベル

In [178]:
net.loss(x, t)

1.3556258597852915

In [179]:
#lossを計算する関数を渡す　
#引数Wにnet.Wが来るが、関数内ではWは用いられず、クラス内でnet.Wが用いられる
def f(W):
    return net.loss(x, t)
#lambda式用いると
f = lambda w:net.loss(x, t)

In [180]:
#定義されたクラスnetのW(net.W)を微妙に変化させて誤差関数の勾配を求める
dW = numerical_gradient(f, net.W)

In [181]:
net.W

array([[-1.59690693, -0.28623791, -0.74587346],
       [ 0.28536994,  1.07691132,  0.43236338]])

In [41]:
print(dW)

[[-1.92757786e-01  1.68729425e-01  2.40283613e-02]
 [ 2.85993451e-09 -2.85993451e-09  0.00000000e+00]]
